#!/usr/bin/perl
#
# quick aes encryption/decryption wih hex strings
# -samy kamkar

use strict;
use Crypt::OpenSSL::AES;

die "usage: $0 [-a (no \\n)] [-d | -e] <0xkey> <0xmessage>\n" unless @ARGV >= 2;

my $crypt;
my $nolf = grep { splice(@ARGV, $_, 1) if $ARGV[$_] eq '-a' } 0 .. $#ARGV;
if ($ARGV[0] eq "-d" || $ARGV[0] eq "-e")
{
  $crypt = shift;
}

my ($key, $msg) = @ARGV;
$key =~ s/^0x//;
$msg =~ s/^0x//;

$key =~ s/(..)/pack("H2", $1)/eg;
$msg =~ s/(..)/pack("H2", $1)/eg;

if (length($msg) % 16 != 0)
{
	print STDERR "padding with " . (16 - (length($msg) % 16)) . " zeros\n\n";
	$msg .= "\x00" x (16 - (length($msg) % 16));
}

#print length($key).$/;
#print "$key\n";

my $cipher = new Crypt::OpenSSL::AES($key);

my $encrypted = $cipher->encrypt($msg);
if ($crypt eq "-e") {
  print unpack("H*", $encrypted);
  print "\n" unless $nolf;
}
elsif (!$crypt)
{
  print "Encrypted: $encrypted\n";
  print "Encrypted: " . unpack("H*", $encrypted) . "\n";
}

my $decrypted = unpack("H*", $cipher->decrypt($msg));
if ($crypt eq "-d")
{
  print $decrypted;
  print "\n" unless $nolf;
}
elsif (!$crypt)
{
  print "Decrypted: " . pack("H*", $decrypted) . "\n";
  print "Decrypted: $decrypted\n";
}