#!/usr/bin/perl

my $CSV = "/Users/samy/code/alexa/top-1m.csv";

use strict;

if (-t STDIN and !@ARGV)
{
	die "usage: $0 <site> [site ...] (or piped in)\n";
}

my %sites;
open(F, "<$CSV") || die "Can't read $CSV: $!";

my $sites = join("|", map { fix($_) } @ARGV);

if (!-t STDIN)
{
	$sites .= "|" if $sites;
	while (<STDIN>)
	{
		chomp;
		$sites .= fix($_) . "|";
	}
	chop($sites);
}

#die $sites;
while (<F>)
{
	chomp;
	my ($i, $url) = split(/,/, $_, 2);
	if ($url =~ /^($sites)$/)
	{
		print "$i\t$url\n";
	}
}
close(F);
	

sub fix
{
	my $url = lc shift;
	$url =~ s/^https?:\/\/(?:www\.)?//i;
	return $url;
}