#!/usr/bin/perl

use strict;

die "usage: $0 <numbers> [NUMBERxTIMES] [...]\n" unless @ARGV;
my ($sum, $count);
foreach (@ARGV)
{
  if (/^(.*)x(.*)$/)
  {
    $count += $2;
    $sum += $1 * $2;
  }
  else
  {
    $count++;
    $sum += $_;
  }
}

print "Count: $count\n";
print "Total: $sum\n";
print "Average: " . int($sum/$count) . "\n";