#!/usr/bin/perl

my $x = shift @ARGV if $ARGV[0] eq "-x";

# no data piped in, use file
if (-t STDIN)
{
  foreach (@ARGV)
  {
    s/(.{8})/($x ? "\\x" : "") . unpack("H2", pack("B8", $1))/eg;
    print;
  }
}
else
{
  while (<>)
  {
    s/(.)/unpack"H2", $1/egs;
    print;
  }
}