#!/usr/bin/perl
#
# convert base64 to ascii
# ignore lines starting with ---

my $out = -t STDOUT ? "\n" : "";
use MIME::Base64;
use strict;

my $type = shift;
if ($type eq "-d")
{
	if (@ARGV)
	{
    print decode($_) . $out for @ARGV;
	}
	else
	{
    print decode($_) while <>;
	}
}
elsif ($type eq "-e")
{
	if (@ARGV)
	{
    print MIME::Base64::encode_base64($_) for @ARGV;
	}
	else
	{
		print MIME::Base64::encode_base64(join("", <>));
	}
}
else
{
	die "usage: $0 <-d | -e> [data | STDIN]\n";
}

sub decode
{
  chomp($_[0]);
  if ($_[0] =~ /^---/)
  {
    print STDERR "NOTICE: Ignoring line: $_\n";
    return "";
  }
  elsif ($_[0] =~ m|[^A-Za-z0-9+/=]|)
  {
    print STDERR "WARNING: Ignoring chars: " . join(",", $_[0] =~ m|([^A-Za-z0-9+/=]+)|g) . "\n";
  }

  return MIME::Base64::decode_base64($_[0]);
}
