#!/usr/bin/perl
#
# backup dot files to dropbox
# -samy kamkar

# file containing files/dirs to ignore
my $IGNORE_FILE = "/Users/samy/.dotignore";

# files to save in home dir
my $SAVE_FILES = ".*";

# where to save to
my $SAVE_TO = "/Users/samy/Dropbox/Mac/Dotfiles";

# path and args to rsync
my $RSYNC = "rsync";
my @RSYNC_ARGS = grep { length } split /\s+/, qq/
	--archive
	--exclude-from=$IGNORE_FILE
	--verbose
/;

use strict;
use lib "/Users/samy/b";
use y;;;

# do this in home
chdir($ENV{HOME});

# get our files to save
my @SAVE = grep { !/^\.\.?$/ } glob($SAVE_FILES);

mkdir($SAVE_TO);
print run($RSYNC, @RSYNC_ARGS, @SAVE, $SAVE_TO);

# xxx don't back these up in the first place
#unlink(map { "$SAVE_TO/$_" } @RM);