#!/usr/bin/perl
#
# run [command] on first file that exists (or doesn't)
#
# firstfile [-n (doesn't exist)] <'cmd' | 'cmd FILE rest'> <files ...>

use y;;;
use Getopt::Long;

my %opts;
GetOptions(\%opts, 'noexist|n') or usage();
usage() unless @ARGV >= 2;
my ($cmd, @files) = @ARGV;

print "files=@files\n";
my $file = first grep { $opts{noexist} ? !-e : -e } @files;
$cmd =~ s/FILE/$file/g || ($cmd .= " '$file'");
execv($cmd);

sub usage
{
  print STDERR "$_[0]\n" if @_;
  die "usage: $0 [-n (doesn't exist)] <'cmd' | 'cmd FILE rest'> <files ...>\n";
}
# s4args -nv
