#!/usr/bin/perl
#
# compile or flash code using particle or platformio
#
# used in vim with ctrl+k/ctrl+l:
# nnoremap <C-k> :w \| !flash -c<CR>
# nnoremap <C-l> :w \| !flash<CR>
#
# -samy kamkar 2020/06/20

my $compile = $ARGV[0] eq "-c" && shift;
my $pio = -e "platformio.ini"; # true if we are working with pio
my $name = shift || "desk" || "p"; # particle board name
my $board = shift || "photon";

my $PARTICLE = "particle";
my $PLATFORMIO = "platformio";

# platformio
if ($pio)
{
  system($compile ? ($PLATFORMIO, qw/run -v/) : ($PLATFORMIO, qw/run -v --target upload/));
}

# particle
else
{
  # dfu over usb
  if ($name eq "usb")
  {
    my $out = `$PARTICLE compile $board`;
    print $out;
    if ($out =~ /saved firmware to: (\S+)/i)
    {
      system($PARTICLE, qw/flash --usb/, $1);
    }
  }

  # flash over network
  else
  {
    system($compile ? ($PARTICLE, qw/-v compile/, $board) : ($PARTICLE, qw/-v flash/, $name));
  }
}