#!/usr/bin/perl
#
# quickly git add/commit/push files
# -samy kamkar 2020/10/25

my $CMD = "git";
my @OPTS = qw//;

use strict;
git("stash") && git("pull") && git("stash", "pop");
git("add", @ARGV) if @ARGV;
#my @changed = (`$CMD status` =~ /: +(\S+)/g);
git("commit", @ARGV ? @ARGV : (`$CMD status` =~ /: +(\S+)/g)) && git("push");

sub git
{
  print STDERR join " ", ">", $CMD, @OPTS, @_, "\n";
  return !system($CMD, @OPTS, @_);
}