#!/usr/bin/perl
#
# output local ip interfaces (all by default)
#
# -samy kamkar
#
# usage: ip [iface | 'gw']

use strict;
use Socket;

my $eth = lc shift;

# ip
if ($eth =~ /^(\d+\.){3}\d+$/)
{
	print "$eth\n";
	exit;
}

# hostname (use inet_ntoa to support /etc/hosts + resolution)
elsif (`ifconfig` !~ /^$eth:/m)
{
	my $inet = inet_aton($eth);
	if ($inet)
	{
		my $addr = inet_ntoa($inet);
		print "$addr\n";
		#  print ((`dig +short $eth`)[0]);
		exit;
	}
}

elsif (!$eth || $eth eq 'gateway' || $eth eq 'gw')
{
	foreach (`/usr/sbin/netstat -nr`)
	{
		if (/^default\s+(\S+)/)
		{
			if ($eth eq 'gw' || $eth eq 'gateway')
			{
				print "$1\n";
				exit;
			}
			else
			{
				print "gateway: $1\n";
				last;
			}
		}
	}
}

my $card;
foreach (`/sbin/ifconfig -a`)
{
	if (/^(\w+):/)
	{
		$card = $1;
	}
	elsif (/inet (\S+)/)
	{
		if ($eth && lc $card eq $eth)
		{
			print "$1\n";
		}
		elsif (!$eth)
		{
			print "$card: $1\n";
		}
	}
}