#!/usr/bin/perl
#
# output local mac addresses (all by default)
#
# -samy kamkar
#
# usage: mac [iface | 'gw']

my $eth = lc shift;
if (!$eth || $eth eq 'gateway' || $eth eq 'gw')
{
	foreach (`/usr/sbin/netstat -nr`)
	{
		if (/^default\s+(\S+)/)
		{
			if ($eth eq 'gw' || $eth eq 'gateway')
			{
				print arpmac($1), "\n";
				exit;
			}
			else
			{
				print "gateway: ", arpmac($1), "\n";
				last;
			}
		}
	}
}

my $card;
foreach (`/sbin/ifconfig -a`)
{
	if (/^(\w+):/)
	{
		$card = $1;
	}
	elsif (/ether (\S+)/)
	{
		if ($eth && lc $card eq $eth)
		{
			print "$1\n";
		}
		elsif (!$eth)
		{
			print "$card: $1\n";
		}
	}
}

sub arpmac
{
  foreach (`arp -na`)
  {
    my @F = split;
    return $F[3] if $F[1] eq "($_[0])";
  }
}