#!/usr/bin/perl
#
# convert proxmark MFU (MIFARE Ultralight) .bin to .eml format
# for proxmark3 loading
#
# -samy kamkar 05/28/2017

my $BLOCKS = 255;
my $UIDLOC = -540; # UID is 540 bytes from the end
my $BLOCKSIZE = 4; # in bytes
use strict;

die "usage: $0 <input .bin>\n" unless @ARGV == 1;
my $input = shift;

open(IN, "<$input") || die "Can't read $input$!";
my $file = join "", <IN>;
close(IN);

my $lines = $BLOCKS;
my $uid = unpack("H14",
  substr($file, length($file) + $UIDLOC, 3) .
  substr($file, (length($file) + $UIDLOC) + 4, 4));
my $pwd = unpack("H8", substr($file, length($file) - 8, 4));
while (length($file))
{
  my $out = substr($file, 0, $BLOCKSIZE, ""); # was 16
  $out = unpack("H*", $out);
  print "$out\n";

  # grab UID
=cut
  if ($BLOCKS - $lines == 12)
  {
    $uid = substr($out, 0, 6);
  }
  elsif ($BLOCKS - $lines == 13)
  {
    $uid .= substr($out, 0, 8);
  }
=cut

  $lines--;
}

# still need to pad to 255 4-byte (8 hex char) blocks
if ($lines > 0)
{
  while ($lines--)
  {
    print "00000000\n";
  }
}

print STDERR "UID: $uid\n";
print STDERR "PWD: $pwd\n";