#!/usr/bin/perl

use y;;;
use strict;

die "usage: [-s(tring)] <data [...]>\n" unless @ARGV || piped();
if ($ARGV[0] eq "-s")
{
  shift;
  print reverse($_) . "\n" for piped() ? <> : @ARGV;
}
else
{
  print reverse piped() ? <> : join(" ", reverse @ARGV);
}