#!/usr/bin/python

import sys
import time
from Quartz.CoreGraphics import *

def scroll_up():
  event = CGEventCreateScrollWheelEvent(None, kCGScrollEventUnitLine, 1, -1)
  CGEventPost(kCGHIDEventTap, event)

scroll_up()